# 线性代数 Python 

## 📖 课程概述

本教程是一份全面的线性代数 Python 实现指南，涵盖以下核心主题：

| 章节 | 内容 | 关键函数 |
|:---|:---|:---|
| 1 | 广义逆矩阵 | `np.dot()`, `np.linalg.pinv()` |
| 2 | 矩阵基本属性 | `np.linalg.matrix_rank()`, `np.trace()`, `np.linalg.det()` |
| 3 | Gram-Schmidt 正交化 | 向量运算 |
| 4 | 矩阵对角化 | `np.linalg.eig()`, `np.diag()` |
| 5 | 矩阵基本运算 | `np.transpose()`, `np.linalg.inv()` |
| 6 | Python 循环基础 | `for`, `range()` |
| 7 | NumPy 索引与 SVD | `np.linalg.svd()` |

---

## 🎯 学习目标

完成本教程后，你将能够：
- 使用 NumPy 进行矩阵的各种运算
- 计算矩阵的特征值和特征向量
- 实现 Gram-Schmidt 正交化过程
- 对矩阵进行对角化分解
- 执行奇异值分解（SVD）

---
## 1️⃣ 广义逆矩阵（Generalized Inverse）

### 📚 理论背景

对于 **奇异矩阵**（不可逆矩阵），我们无法计算常规逆矩阵。此时可以使用**广义逆矩阵**（或伪逆矩阵）。

**定义**：矩阵 $B$ 是矩阵 $A$ 的广义逆，当且仅当满足以下条件：
$$ABA = A$$

> 💡 **提示**：NumPy 提供 `np.linalg.pinv()` 函数来计算 Moore-Penrose 伪逆。

In [4]:
# 示例：验证广义逆矩阵的性质
import numpy as np

# 定义一个奇异矩阵 A（行列式为 0，不可逆）
A = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]])

# 定义矩阵 B 作为 A 的一个广义逆
B = np.array([[-5/3, 2/3, 0],
              [4/3, -1/3, 0], 
              [0, 0, 0]])

# 验证 ABA = A
C = np.dot(A, B)      # 先计算 AB
result = np.dot(C, A) # 再计算 (AB)A

print("原矩阵 A:")
print(A)
print("\n广义逆矩阵 B:")
print(B)
print("\n验证 ABA = A:")
print(result)
print("\n✅ 验证成功！" if np.allclose(result, A) else "❌ 验证失败")

原矩阵 A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

广义逆矩阵 B:
[[-1.66666667  0.66666667  0.        ]
 [ 1.33333333 -0.33333333  0.        ]
 [ 0.          0.          0.        ]]

验证 ABA = A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

✅ 验证成功！


---
## 2️⃣ 矩阵基本属性分析

### 📚 核心概念

| 属性 | 定义 | NumPy 函数 |
|:---|:---|:---|
| **秩 (Rank)** | 矩阵的线性无关行/列的最大数量 | `np.linalg.matrix_rank()` |
| **迹 (Trace)** | 主对角线元素之和 | `np.trace()` |
| **行列式 (Determinant)** | 矩阵的标量特征值 | `np.linalg.det()` |
| **特征值 (Eigenvalues)** | 满足 $Av = \lambda v$ 的 $\lambda$ | `np.linalg.eig()` |
| **转置 (Transpose)** | 行列互换 | `np.transpose()` 或 `.T` |

### 🔑 重要性质

- 若 $\det(A) = 0$，则矩阵**奇异**，不可逆
- 特征值的乘积等于行列式
- 特征值的和等于迹

In [5]:
# 示例：分析幂等矩阵的属性
import numpy as np

# 定义一个幂等矩阵 (A² = A)
A1 = np.array([[1, 0, 0],
              [0, 1/2, 1/2], 
              [0, 1/2, 1/2]])

print("=" * 50)
print("矩阵 A1:")
print(A1)
print("=" * 50)

# 验证幂等性
print("\n🔹 幂等性验证 (A² = A):")
A1_squared = np.dot(A1, A1)
print(f"A1² = \n{A1_squared}")
print(f"✅ 是幂等矩阵" if np.allclose(A1_squared, A1) else "❌ 不是幂等矩阵")

# 基本属性
print("\n🔹 基本属性:")
print(f"  秩 (Rank):     {np.linalg.matrix_rank(A1)}")
print(f"  迹 (Trace):    {np.trace(A1)}")
print(f"  行列式 (Det):  {np.linalg.det(A1):.6f}")

# 转置
print(f"\n🔹 转置矩阵 A1ᵀ:")
print(np.transpose(A1))

# 判断可逆性
print("\n🔹 可逆性判断:")
det = np.linalg.det(A1)
if np.isclose(det, 0):
    print("  ⚠️ 矩阵奇异（行列式为 0），不可逆！")
else:
    print(f"  ✅ 矩阵可逆，逆矩阵为:\n{np.linalg.inv(A1)}")

矩阵 A1:
[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]

🔹 幂等性验证 (A² = A):
A1² = 
[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]
✅ 是幂等矩阵

🔹 基本属性:
  秩 (Rank):     2
  迹 (Trace):    2.0
  行列式 (Det):  0.000000

🔹 转置矩阵 A1ᵀ:
[[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]

🔹 可逆性判断:
  ⚠️ 矩阵奇异（行列式为 0），不可逆！


In [6]:
# 特征值与特征向量分析
print("🔹 特征值与特征向量:")
eigenvalues, eigenvectors = np.linalg.eig(A1)

print(f"  特征值: {eigenvalues}")
print(f"\n  特征向量矩阵:\n{eigenvectors}")

# 详细展示每对特征值和特征向量
print("\n📊 特征值-特征向量配对:")
for i, (val, vec) in enumerate(zip(eigenvalues, eigenvectors.T)):
    print(f"  λ{i+1} = {val:.4f}")
    print(f"  v{i+1} = {vec}")
    # 验证 Av = λv
    Av = A1 @ vec
    lambda_v = val * vec
    print(f"  验证 Av = λv: {np.allclose(Av, lambda_v)}")
    print()

🔹 特征值与特征向量:
  特征值: [1.00000000e+00 1.11022302e-16 1.00000000e+00]

  特征向量矩阵:
[[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]

📊 特征值-特征向量配对:
  λ1 = 1.0000
  v1 = [0.         0.70710678 0.70710678]
  验证 Av = λv: True

  λ2 = 0.0000
  v2 = [ 0.          0.70710678 -0.70710678]
  验证 Av = λv: True

  λ3 = 1.0000
  v3 = [1. 0. 0.]
  验证 Av = λv: True



---
## 3️⃣ Gram-Schmidt 正交化过程

### 📚 理论背景

**Gram-Schmidt 正交化**是将一组线性无关的向量转换为**正交向量组**的算法。

### 🔢 算法步骤

给定向量 $\{x_1, x_2, \ldots, x_n\}$，生成正交向量 $\{v_1, v_2, \ldots, v_n\}$：

$$v_1 = x_1$$

$$v_k = x_k - \sum_{j=1}^{k-1} \frac{\langle x_k, v_j \rangle}{\langle v_j, v_j \rangle} v_j$$

### 📐 标准化（正交规范化）

将正交向量转换为**单位向量**（长度为 1）：

$$u_i = \frac{v_i}{\|v_i\|}$$

In [7]:
# Gram-Schmidt 正交化示例
import numpy as np

# 原始向量
x1 = np.array([3, 6, 0])
x2 = np.array([1, 2, 2])

print("=" * 50)
print("原始向量:")
print(f"  x1 = {x1}")
print(f"  x2 = {x2}")
print("=" * 50)

# Step 1: v1 = x1
v1 = x1

# Step 2: v2 = x2 - proj_{v1}(x2)
# 投影系数 c = <x2, v1> / <v1, v1>
c1 = np.dot(x2, v1) / np.dot(v1, v1)
v2 = x2 - c1 * v1

print("\n🔹 正交化过程:")
print(f"  投影系数 c = <x2,v1>/<v1,v1> = {c1:.4f}")
print(f"  v1 = {v1}")
print(f"  v2 = x2 - c·v1 = {v2}")

# 验证正交性
print(f"\n🔹 验证正交性:")
print(f"  <v1, v2> = {np.dot(v1, v2):.6f}")
print(f"  ✅ 向量正交！" if np.isclose(np.dot(v1, v2), 0) else "  ❌ 向量不正交")

# 标准化为单位向量
u1 = v1 / np.linalg.norm(v1)
u2 = v2 / np.linalg.norm(v2)

print(f"\n🔹 标准化（正交规范基）:")
print(f"  u1 = {u1}")
print(f"  u2 = {u2}")
print(f"  |u1| = {np.linalg.norm(u1):.4f}")
print(f"  |u2| = {np.linalg.norm(u2):.4f}")

原始向量:
  x1 = [3 6 0]
  x2 = [1 2 2]

🔹 正交化过程:
  投影系数 c = <x2,v1>/<v1,v1> = 0.3333
  v1 = [3 6 0]
  v2 = x2 - c·v1 = [0. 0. 2.]

🔹 验证正交性:
  <v1, v2> = 0.000000
  ✅ 向量正交！

🔹 标准化（正交规范基）:
  u1 = [0.4472136  0.89442719 0.        ]
  u2 = [0. 0. 1.]
  |u1| = 1.0000
  |u2| = 1.0000


---
## 4️⃣ 矩阵对角化

### 📚 理论背景

若存在可逆矩阵 $P$ 使得：
$$A = PDP^{-1}$$

其中 $D$ 是**对角矩阵**，则称 $A$ 可对角化。

### 🔑 关键定理

- $P$ 的列是 $A$ 的特征向量
- $D$ 的对角线元素是对应的特征值
- 若 $A$ 是**对称矩阵**，则 $P$ 是**正交矩阵**（$P^{-1} = P^T$）

### ⚠️ 对角化条件

矩阵 $A$ 可对角化当且仅当 $A$ 有 $n$ 个线性无关的特征向量。

In [17]:
# 定义对角化函数
import numpy as np

def diagonalize_matrix(A):
    """
    对角化矩阵 A
    
    参数:
        A: 方阵 (n×n numpy array)
    
    返回:
        D: 对角矩阵（特征值在对角线上）
        P: 正交矩阵（列为归一化的特征向量）
    """
    # 计算特征值和特征向量
    eigenvalues, eigenvectors = np.linalg.eig(A)
    
    print(f"特征值: {eigenvalues}")
    print(f"特征向量矩阵:\n{eigenvectors}")
    
    # 构造对角矩阵 D
    D = np.diag(eigenvalues)
    
    # 归一化特征向量得到 P
    n = A.shape[0]
    P = np.zeros((n, n))
    
    for i in range(n):
        # 归一化每个特征向量
        norm = np.linalg.norm(eigenvectors[:, i])
        P[:, i] = eigenvectors[:, i] / norm
            
    return D, P

In [9]:
# 测试对角化（使用对称矩阵）
A = np.array([[7, 2],
              [2, 4]])

print("=" * 50)
print("原矩阵 A:")
print(A)
print("=" * 50)

# 对角化
D, P = diagonalize_matrix(A)

print(f"\n🔹 对角化结果: A = P D P^T")
print(f"\nP (正交矩阵):\n{P}")
print(f"\nD (对角矩阵):\n{D}")

# 验证 P 是正交矩阵
PP_T = P @ P.T
print(f"\n🔹 验证 P 是正交矩阵 (PP^T = I):")
print(np.round(PP_T, 10))
print(f"✅ P 是正交矩阵！" if np.allclose(PP_T, np.eye(2)) else "❌ P 不是正交矩阵")

# 验证 A = P D P^T
A_reconstructed = P @ D @ P.T
print(f"\n🔹 验证 A = P D P^T:")
print(np.round(A_reconstructed, 10))
print(f"✅ 对角化成功！" if np.allclose(A_reconstructed, A) else "❌ 对角化失败")

原矩阵 A:
[[7 2]
 [2 4]]
特征值: [8. 3.]
特征向量矩阵:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

🔹 对角化结果: A = P D P^T

P (正交矩阵):
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]

D (对角矩阵):
[[8. 0.]
 [0. 3.]]

🔹 验证 P 是正交矩阵 (PP^T = I):
[[ 1. -0.]
 [-0.  1.]]
✅ P 是正交矩阵！

🔹 验证 A = P D P^T:
[[7. 2.]
 [2. 4.]]
✅ 对角化成功！


---
## 5️⃣ 矩阵基本运算

### 📊 运算类型一览

| 运算 | 符号 | NumPy 实现 |
|:---|:---|:---|
| 加法 | $A + B$ | `A + B` 或 `np.add(A, B)` |
| 减法 | $A - B$ | `A - B` 或 `np.subtract(A, B)` |
| 数乘 | $cA$ | `c * A` 或 `np.multiply(A, c)` |
| 矩阵乘法 | $AB$ | `A @ B` 或 `np.dot(A, B)` |
| 元素乘法 | $A \odot B$ | `A * B` |
| 转置 | $A^T$ | `A.T` 或 `np.transpose(A)` |
| 逆矩阵 | $A^{-1}$ | `np.linalg.inv(A)` |

> ⚠️ **注意**：`@` 运算符用于矩阵乘法，`*` 用于**逐元素**乘法！

In [10]:
# 矩阵基本运算示例
import numpy as np

# 定义矩阵
A = np.array([[1, 2, 0],
              [2, 3, 5],
              [1, 4, 4]])

B = np.array([[1, 0, 0],
              [2, 1, 1],
              [0, 0, 3]])

print("矩阵 A:")
print(A)
print("\n矩阵 B:")
print(B)

# 矩阵加法
print("\n" + "=" * 50)
print("🔹 矩阵加法 A + B:")
print(A + B)

# 矩阵减法
print("\n🔹 矩阵减法 A - B:")
print(np.subtract(A, B))

# 数乘
c = 2
print(f"\n🔹 数乘 {c} × A:")
print(c * A)

# 矩阵乘法
print("\n🔹 矩阵乘法 A @ B:")
print(A @ B)

矩阵 A:
[[1 2 0]
 [2 3 5]
 [1 4 4]]

矩阵 B:
[[1 0 0]
 [2 1 1]
 [0 0 3]]

🔹 矩阵加法 A + B:
[[2 2 0]
 [4 4 6]
 [1 4 7]]

🔹 矩阵减法 A - B:
[[0 2 0]
 [0 2 4]
 [1 4 1]]

🔹 数乘 2 × A:
[[ 2  4  0]
 [ 4  6 10]
 [ 2  8  8]]

🔹 矩阵乘法 A @ B:
[[ 5  2  2]
 [ 8  3 18]
 [ 9  4 16]]


In [11]:
# 转置与逆矩阵
print("🔹 矩阵转置 A^T:")
print(A.T)

print(f"\n🔹 矩阵秩 rank(A) = {np.linalg.matrix_rank(A)}")

# 逆矩阵
print("\n🔹 逆矩阵 A^(-1):")
A_inv = np.linalg.inv(A)
print(A_inv)

# 验证 AA^(-1) = I
print("\n🔹 验证 A × A^(-1) = I:")
identity = A @ A_inv
print(np.round(identity, 10))

# 2x2 矩阵逆的快速计算公式示例
C = np.array([[3, 2],
              [7, 5]])
print("\n" + "=" * 50)
print("🔹 2×2 矩阵快速求逆:")
print(f"矩阵 C:\n{C}")
print(f"\n行列式 det(C) = {np.linalg.det(C):.4f}")
print(f"\nC^(-1):\n{np.linalg.inv(C)}")

🔹 矩阵转置 A^T:
[[1 2 1]
 [2 3 4]
 [0 5 4]]

🔹 矩阵秩 rank(A) = 3

🔹 逆矩阵 A^(-1):
[[ 0.57142857  0.57142857 -0.71428571]
 [ 0.21428571 -0.28571429  0.35714286]
 [-0.35714286  0.14285714  0.07142857]]

🔹 验证 A × A^(-1) = I:
[[ 1. -0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]

🔹 2×2 矩阵快速求逆:
矩阵 C:
[[3 2]
 [7 5]]

行列式 det(C) = 1.0000

C^(-1):
[[ 5. -2.]
 [-7.  3.]]


---
## 6️⃣ Python 循环基础

### 🔄 for 循环语法

```python
for variable in iterable:
    # 循环体
```

### 📋 range() 函数

| 用法 | 说明 |
|:---|:---|
| `range(n)` | 生成 0 到 n-1 |
| `range(start, stop)` | 生成 start 到 stop-1 |
| `range(start, stop, step)` | 以 step 为步长 |

### 🛡️ 异常处理

```python
try:
    # 可能出错的代码
except ErrorType:
    # 错误处理
```

In [12]:
# 循环基础示例

# 基础 for 循环
print("🔹 基础 for 循环:")
for i in range(3):
    print(f"  i = {i}")

# 带步长的 range
print("\n🔹 带步长的 range(5, 14, 3):")
for i in range(5, 14, 3):
    print(f"  i = {i}")

# range 转列表
print(f"\n🔹 range(5) 转列表: {list(range(5))}")
print(f"🔹 sum(range(5)) = {sum(range(5))}")

# 遍历列表
print("\n🔹 遍历字符串列表:")
for char in ['A', 'B', 'C']:
    print(f"  {char}")

# 使用 enumerate
print("\n🔹 使用 enumerate 获取索引和值:")
colors = ['红', '绿', '蓝']
for idx, color in enumerate(colors):
    print(f"  索引 {idx}: {color}")

🔹 基础 for 循环:
  i = 0
  i = 1
  i = 2

🔹 带步长的 range(5, 14, 3):
  i = 5
  i = 8
  i = 11

🔹 range(5) 转列表: [0, 1, 2, 3, 4]
🔹 sum(range(5)) = 10

🔹 遍历字符串列表:
  A
  B
  C

🔹 使用 enumerate 获取索引和值:
  索引 0: 红
  索引 1: 绿
  索引 2: 蓝


In [13]:
# 循环中的异常处理
print("🔹 异常处理示例（除法运算）:")

denominators = [2, 1, 0, -1]

for d in denominators:
    try:
        result = 1 / d
        print(f"  1/{d} = {result:.4f}")
    except ZeroDivisionError:
        print(f"  1/{d} = ⚠️ 错误：除数不能为零！")

🔹 异常处理示例（除法运算）:
  1/2 = 0.5000
  1/1 = 1.0000
  1/0 = ⚠️ 错误：除数不能为零！
  1/-1 = -1.0000


---
## 7️⃣ NumPy 索引与求和

### 📑 数组索引语法

| 语法 | 说明 |
|:---|:---|
| `x[i, j]` | 访问第 i 行第 j 列元素 |
| `x[i, :]` | 获取第 i 行 |
| `x[:, j]` | 获取第 j 列 |
| `x[a:b, c:d]` | 获取子矩阵 |

### 📊 轴（Axis）求和

| 操作 | 说明 |
|:---|:---|
| `x.sum()` | 所有元素求和 |
| `x.sum(axis=0)` | 按列求和（垂直方向↓） |
| `x.sum(axis=1)` | 按行求和（水平方向→） |

In [14]:
# NumPy 索引示例
import numpy as np

x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print("矩阵 x:")
print(x)

print("\n" + "=" * 50)
print("🔹 索引操作:")
print(f"  x[0, 0] = {x[0, 0]}  (第1行第1列)")
print(f"  x[1, 2] = {x[1, 2]}  (第2行第3列)")

print(f"\n🔹 获取第0列: x[:, 0] = {x[:, 0]}")
print(f"🔹 获取第1行: x[1, :] = {x[1, :]}")

print(f"\n🔹 获取子矩阵 x[:, 1:3]:")
print(x[:, 1:3])

print("\n" + "=" * 50)
print("🔹 轴求和:")
print(f"  全部求和    x.sum()      = {x.sum()}")
print(f"  按列求和    x.sum(axis=0) = {x.sum(axis=0)}")
print(f"  按行求和    x.sum(axis=1) = {x.sum(axis=1)}")

矩阵 x:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

🔹 索引操作:
  x[0, 0] = 1  (第1行第1列)
  x[1, 2] = 6  (第2行第3列)

🔹 获取第0列: x[:, 0] = [1 4 7]
🔹 获取第1行: x[1, :] = [4 5 6]

🔹 获取子矩阵 x[:, 1:3]:
[[2 3]
 [5 6]
 [8 9]]

🔹 轴求和:
  全部求和    x.sum()      = 45
  按列求和    x.sum(axis=0) = [12 15 18]
  按行求和    x.sum(axis=1) = [ 6 15 24]


---
## 8️⃣ 奇异值分解（SVD）

### 📚 理论背景

**奇异值分解**是将任意 $m \times n$ 矩阵分解为三个矩阵的乘积：

$$A = U \Sigma V^T$$

其中：
- $U$：$m \times m$ 正交矩阵（左奇异向量）
- $\Sigma$：$m \times n$ 对角矩阵（奇异值）
- $V^T$：$n \times n$ 正交矩阵的转置（右奇异向量）

### 🎯 应用场景

| 领域 | 应用 |
|:---|:---|
| 数据压缩 | 图像压缩 |
| 推荐系统 | 潜在因子分析 |
| 降维 | PCA 的实现基础 |
| 数值计算 | 求解最小二乘问题 |

### ⚠️ 注意

NumPy 的 `svd()` 返回的 $\Sigma$ 是**一维数组**（仅包含奇异值），需要手动构建对角矩阵。

In [15]:
# SVD 分解示例 1：m < n 的情况（2×3 矩阵）
import numpy as np

A = np.array([[4, 11, 14],
              [8, 7, -2]])

print("=" * 60)
print("SVD 分解示例 1：2×3 矩阵（行数 < 列数）")
print("=" * 60)
print(f"\n原矩阵 A ({A.shape[0]}×{A.shape[1]}):")
print(A)

# 执行 SVD 分解
U, S, VT = np.linalg.svd(A)

# 构建 Σ 矩阵
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:len(S), :len(S)] = np.diag(S)

print(f"\n🔹 U ({U.shape[0]}×{U.shape[1]}) - 左奇异向量:")
print(U)

print(f"\n🔹 Σ ({Sigma.shape[0]}×{Sigma.shape[1]}) - 奇异值对角矩阵:")
print(Sigma)

print(f"\n🔹 V^T ({VT.shape[0]}×{VT.shape[1]}) - 右奇异向量转置:")
print(VT)

# 验证重构
A_reconstructed = U @ Sigma @ VT
print("\n🔹 验证 A = U Σ V^T:")
print(np.round(A_reconstructed, 10))
print(f"✅ SVD 分解正确！" if np.allclose(A_reconstructed, A) else "❌ SVD 分解错误")

SVD 分解示例 1：2×3 矩阵（行数 < 列数）

原矩阵 A (2×3):
[[ 4 11 14]
 [ 8  7 -2]]

🔹 U (2×2) - 左奇异向量:
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]

🔹 Σ (2×3) - 奇异值对角矩阵:
[[18.97366596  0.          0.        ]
 [ 0.          9.48683298  0.        ]]

🔹 V^T (3×3) - 右奇异向量转置:
[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]

🔹 验证 A = U Σ V^T:
[[ 4. 11. 14.]
 [ 8.  7. -2.]]
✅ SVD 分解正确！


In [16]:
# SVD 分解示例 2：m > n 的情况（3×2 矩阵）
A2 = np.array([[1, -1],
               [-2, 2],
               [2, -2]])

print("=" * 60)
print("SVD 分解示例 2：3×2 矩阵（行数 > 列数）")
print("=" * 60)
print(f"\n原矩阵 A ({A2.shape[0]}×{A2.shape[1]}):")
print(A2)

# 执行 SVD 分解
U2, S2, VT2 = np.linalg.svd(A2)

# 构建 Σ 矩阵
Sigma2 = np.zeros((A2.shape[0], A2.shape[1]))
Sigma2[:len(S2), :len(S2)] = np.diag(S2)

print(f"\n🔹 U ({U2.shape[0]}×{U2.shape[1]}):")
print(np.round(U2, 4))

print(f"\n🔹 Σ ({Sigma2.shape[0]}×{Sigma2.shape[1]}):")
print(np.round(Sigma2, 4))

print(f"\n🔹 V^T ({VT2.shape[0]}×{VT2.shape[1]}):")
print(np.round(VT2, 4))

# 验证重构
A2_reconstructed = U2 @ Sigma2 @ VT2
print("\n🔹 验证 A = U Σ V^T:")
print(np.round(A2_reconstructed, 10))
print(f"✅ SVD 分解正确！" if np.allclose(A2_reconstructed, A2) else "❌ SVD 分解错误")

# 分析秩
print(f"\n📊 矩阵秩分析:")
print(f"  理论秩 = min(m, n) = min({A2.shape[0]}, {A2.shape[1]}) = {min(A2.shape)}")
print(f"  非零奇异值数量 = {np.sum(S2 > 1e-10)}")
print(f"  实际秩 = {np.linalg.matrix_rank(A2)}")

SVD 分解示例 2：3×2 矩阵（行数 > 列数）

原矩阵 A (3×2):
[[ 1 -1]
 [-2  2]
 [ 2 -2]]

🔹 U (3×3):
[[-0.3333  0.6667 -0.6667]
 [ 0.6667  0.6667  0.3333]
 [-0.6667  0.3333  0.6667]]

🔹 Σ (3×2):
[[4.2426 0.    ]
 [0.     0.    ]
 [0.     0.    ]]

🔹 V^T (2×2):
[[-0.7071  0.7071]
 [ 0.7071  0.7071]]

🔹 验证 A = U Σ V^T:
[[ 1. -1.]
 [-2.  2.]
 [ 2. -2.]]
✅ SVD 分解正确！

📊 矩阵秩分析:
  理论秩 = min(m, n) = min(3, 2) = 2
  非零奇异值数量 = 1
  实际秩 = 1


---
## 📝 总结

### 🎯 核心函数速查表

| 功能 | NumPy 函数 |
|:---|:---|
| 矩阵乘法 | `np.dot(A, B)` 或 `A @ B` |
| 转置 | `A.T` 或 `np.transpose(A)` |
| 逆矩阵 | `np.linalg.inv(A)` |
| 伪逆 | `np.linalg.pinv(A)` |
| 行列式 | `np.linalg.det(A)` |
| 秩 | `np.linalg.matrix_rank(A)` |
| 迹 | `np.trace(A)` |
| 特征值/向量 | `np.linalg.eig(A)` |
| SVD | `np.linalg.svd(A)` |

### 📚 延伸学习

- **NumPy 官方文档**: https://numpy.org/doc/
- **线性代数基础**: Gilbert Strang《线性代数及其应用》
- **数值线性代数**: Trefethen & Bau《数值线性代数》

---

🎉 **恭喜完成本教程！** 现在你已经掌握了使用 Python 进行线性代数计算的核心技能。